### ISSUE TITLE
can't get online successfully,and i tried by cobaltstrike 4.4

### ISSUE THREAD

**Issue by m0s30** [icyguider/Shhhloader#16]
Generated details（x64）：
![image](https://user-images.githubusercontent.com/54650671/171571927-ec4a5dc6-06b4-4edc-b1c5-bdc717e616f0.png)

when i run it：
![image](https://user-images.githubusercontent.com/54650671/171572035-7aa9eb77-4dfc-4f33-91f2-40d34ced6d33.png)

os: win10 10.0.17763

**Comment by icyguider** [comment]
Hi @PANDA-MS.

A few notes.
- I tested this out using the exact same version of Cobalt Strike (4.4), the exact same build of Windows 10 (17763), and the exact same command as shown in your screenshot. I received no errors upon execution of the file, and I received a beacon back with no issues at all. Here is a short video showing this: https://www.youtube.com/watch?v=IxiZb_ytrgA

- I have noticed that for some reason multiple people using Cobalt Strike (seemingly only version 4.4) are having issues that I am unable to replicate as seen in the above video. I am really not sure why this is happening. Because I am unable to replicate the issue on my end, only you can really try to figure out what the problem is. I recommend trying other shellcode payloads (x64 Meterpreter for example), other target systems, or updating your Cobalt Strike version. By doing this I'm sure you could eventually figure out the issue if you care enough.

- The first screenshot you posted shows you using the "QueueUserAPC" injection method, however the 2nd screenshot contains text that is only found in the code for "ProcessHollow" method.  I've assumed you tried both and they aren't working for you and are throwing similar errors upon execution? Either way, I am not able to replicate these errors, so I don't think I will be able to figure it out for you.

**Comment by j0t4s3c** [comment]
Hello, i hope that this feedback can help to improve this awesome tool.
Im doing some test with the same calc.bin shellcode that you generated in this video:
https://www.youtube.com/watch?v=ttCRiobmulU&list=LL&index=37 and its being detected by Windows defender.
I also tried disabling Cloud-delivered protection as you recommended in some comment and still triggering it.
I tried with all the shellcode execution methods also with different processes to inject into like notepad.exe, explorer.exe without success.
The only way to execute it successfully was disabling Real-time protection.
![Shellcode](https://user-images.githubusercontent.com/89747852/173203095-f5728520-8651-463f-947a-9642348657fd.png)
![Windows](https://user-images.githubusercontent.com/89747852/173203094-b33b66e8-bd9b-455a-ac08-d01f99d15918.png)

**Comment by icyguider** [comment]
@j0t4s3c Yes I've seen that happen before. As months go by, the detection rate of any public tool designed to bypass AV is almost guaranteed to get worse. The goal of this project was never to provide something that was future proof in terms of being detected or to constantly update it so that it would remain undetected, but rather the goal was to provide something that was working on release that people could learn from and potentially modify for their own needs.

With that being said, I do plan on pushing some improvements occasionally that may address the newer detection issues. For example, in the next couple weeks there will be an update that makes the code compatible with Obfuscator-LLVM. It will also provide an option to store shellcode in a stealthier way. 

I hope these updates will make it much harder for AVs to create signatures for the tool as time goes on, but as I said, any public tool that's widely used will definitely start to get detected as months go by. That's why I encourage everyone who uses the tool to make their own private modifications to it so that they don't have to wait for me to update the tool every few months or longer.

**Comment by j0t4s3c** [comment]
Thanks for your work

**Comment by icyguider** [comment]
Closing this issue as it's been a couple months since the last reply and I was never able to replicate the original issue. Also, the newest features of the update pushed today should hopefully address some of the other issues discussed in this thread.
