### ISSUE TITLE
GetSyscallStub not working

### ISSUE THREAD

**Issue by qgrosperrin** [icyguider/Shhhloader#22]
Hi. 
I'm trying a Cobalt Strike (4.7) x64 stageless shellcode, and facing some issues against a Win10 machine with:
- GetSyscallStub option. When used, I get no beacon
- EnumDisplayMonitors or ModuleStomping options. When used, I get no beacon

The only option that works for me is using default 'QueueUserAPC' without GetSyscallStub.
Are you aware of these limitations or am I doing something wrong ? My AV is disabled for test purposes and I don't have any EDR either

Thanks

**Comment by icyguider** [comment]
Hi @qgrosperrin.

Regarding the ModuleStomping method, it is currently only compatible with staged payloads as is already outlined  in the README file for this project: https://github.com/icyguider/Shhhloader/blob/main/README.md?plain=1#L67

Regarding everything else, GetSyscallStub is working perfectly fine for me against multiple different Windows 10 & Server 2019 systems. Here's a video demonstrating how I can get a CS 4.7 beacon back using GetSyscallStub with all 7 shellcode injection techniques this tool offers: https://www.youtube.com/watch?v=EsW_9mHe6fE

Given that I am unable to replicate the issue you are having, my recommendation would be to try other simple shellcode (like msf's windows/x64/exec) to see if your issue is somehow related to your specific Cobalt Strike configuration. I also highly suggest using the `-v` flag with Shhhloader when testing so that you can actually see what the tool is doing upon execution and if it is failing on a certain step.

I also suggest spinning up a new Linux VM/container to generate your shellcode. This would negate any issue that may be arising due to your compilation environment. For example: I just spun up a fresh Debian 11 VM, installed mingw-w64 with apt, cloned Shhhloader, used the EnumDisplayMonitors method with GetSyscallStub, and the generated file executed perfectly fine on a Windows 10 host.

**Comment by icyguider** [comment]
Closing this issue as I was unable to reproduce and there hasn't been any update for a couple of months.

Somewhat related but not really; I did update the ModuleStomping method and it should now work with all stageless/large payloads. Again that's not related to whatever issue you were having, it's just a FYI for anyone who may read this thread in the future.

**Comment by qgrosperrin** [comment]
Thanks for your support !
I will try to find some time to troubleshoot this on my end.

**Comment by qgrosperrin** [comment]
Hi, 
I'm still having that issue... Did you try with -d to generate a DLL when you tried to replicate the issue ? 
I can see from the Youtube link you posted, all the payloads generated are .exe and those work for us as well, but we cannot get DLL to work with EnumDisplayMonitors.

**Comment by qgrosperrin** [comment]
Renamed title to be more accurate.
Turns out if I replace the stub at https://github.com/icyguider/Shhhloader/blob/57b154a09811d5349e701fdffe0d6ee567681130/Shhhloader.py#L1315 with 
```
rundll_stub = """
BOOL WINAPI DllMain (HANDLE hDll, DWORD dwReason, LPVOID lpReserved){
    //HANDLE threadhandle;
    switch(dwReason){
        case DLL_PROCESS_ATTACH:
        case DLL_PROCESS_DETACH:
        case DLL_THREAD_ATTACH:
        case DLL_THREAD_DETACH:
            break;
    }
    return TRUE;
}
```

then the 'EnumDisplayMonitors' injection for me using DLL.
` python3 Shhhloader.py beaconx64.bin -g -w -d -m EnumDisplayMonitors -v -o qenumdisplay.dll -ns`
executing with `rundll32 qenumdisplay.dll,main`
