### ISSUE TITLE
AMSI bypass gone?

### ISSUE THREAD

**Issue by Esek11** [icyguider/Shhhloader#25]
In the newest version the -a flag is gone.  Is that a feature which will be returning to future versions?

**Comment by icyguider** [comment]
Hi @Esek11,

The "AMSI bypass" feature was removed a while back because as I learned more about AMSI, I didn't believe patching it was actually useful for this tool. As far as I know, AMSI is only responsible for detecting malicious PowerShell, JavaScript/VBA, and .NET code. As the stub for this tool is written in C++, I don't believe that disabling AMSI offers any real benefit. 

The only use case where I could see an AMSI bypass helping is if you're attempting to execute shellcode for a .NET file generated by a tool like donut. However, donut generated shellcode already automatically patches AMSI by default, so it's not really something Shhhloader needs to do at least for that use case. If more use cases are presented to me, I might considering re-adding the feature. Thanks for your interest in the project.
