### ISSUE TITLE
PE's console issue

### ISSUE THREAD

**Issue by G0ne** [icyguider/Shhhloader#34]
I tried to combine https://github.com/EgeBalci/amber and your tool ( which is awesome ) for mimikatz
Once the .exe has been generated, i execute it, but nothing happens.. probably because the console part got lost somehow
Can you please take a look at it? ( if i execute just the shellcode of the .bin generate from amber it works fine )

Command line used:
./amber -f ../mimigo.exe -v -e 3 --iat -l 2
python3 Shhhloader.py -p explorer.exe --sandbox sleep -v -o a.exe ../mimigo.exe.bin

**Comment by icyguider** [comment]
Hi @G0ne.

A couple notes:

1.  To use tools that require an interactive console (like mimikatz) with Shhhloader, you must specify either the `CurrentThread` or `EnumDisplayMonitors`  executions methods. This is because these methods execute the shellcode in the current stub process unlike the process injection techniques, allowing for an interactive console. You must also supply the -v flag. To see a successful demonstration of this using [Donut](https://github.com/TheWover/donut) and Shhhloader, see the following closed issue: https://github.com/icyguider/Shhhloader/issues/24

2. I briefly tried to use amber + mimikatz with the options described above, but I was not able to get successful execution. I believe this is because Shhhloader has problems executing shellcode encoded with SGN. So for now, I'd say amber is incompatible with Shhhloader and I'd recommend using Donut if you want to achieve a similar result with this tool.

Hope this helps!

**Comment by G0ne** [comment]
Thanks for the notes! Hope to see soon shhhloader being compatible with amber, that combo would be broken(:
