### ISSUE TITLE
Shhhloader PrivEsc issues

### ISSUE THREAD

**Issue by GrappleStiltskin** [icyguider/Shhhloader#39]
I've had issues with getting a successful privilege escalation with a Shhhloader payload. I've tried this with Meterpreter and Cobalt Strike beacons, and I've tried it for DLL Hijacking and Service Binary Hijacking. I also changed the process from explore.exe to rundll32.exe. It doesn't get any callbacks on Meterpreter. I'll get a callback on CS, but it's always in a normal user session. Is there a reason for this?

**Comment by icyguider** [comment]
Hi @GrappleStiltskin,

Apologies for the rather late response. What you are experiencing is partly the expected behavior of Shhhloader's PPID spoofing functionality. The reason you are getting a callback as a normal user is because Shhhloader is configured to spoof unprivileged processes by default.

This can be overridden by specifying the `--ppid-priv` flag in addition to the `--ppid` flag with the name of a privileged process. Alternatively, PPID spoofing can be turned off altogether with the `-np` flag. Doing this will allow the newly created process to execute your beacon as administrator, giving you a admin callback.

As for why you don't get *any* callbacks when using Meterpreter, I have no idea why this could be the case. I recently tested Meterpreter and it worked fine, and the fact that your CS beacon works makes me think it could be something specific to your MSF/Meterpreter config. If you ever figure out what's going on there, feel free to open a new issue if it's something I can fix within the tool.
