### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by rotarydrone** [icyguider/Shhhloader#8]
Strip debug information from the binary for opsec and size reduction:  `x86_64-w64-mingw32-strip --strip-all`

Add `skCrypter.h` headers and wrap the key with `skCrypt("key")` so that it is not a plaintext string: [https://github.com/skadro-official/skCrypter](https://github.com/skadro-official/skCrypter)

**Comment by icyguider** [comment]
Sorry about replying to this issue so late.

Thank you for your recommendations. I believe your first recommendation has already been implemented since 2/18 as a result of [this pull request](https://github.com/icyguider/Shhhloader/pull/5) being merged.

As for your second recommendation, string encryption is definitely something I want to be available as an option at some point. I plan to work on it and release an update that implements it sometime in the future. 

Thanks!
